### ISSUE TITLE
Hide Focused Player when in third person

### ISSUE THREAD

**Issue by drweissbrot** [drweissbrot/cs-hud#102]

**Comment by drweissbrot** [comment]
Unsure if this is possible at the moment, it looks like CS2 keeps sending out the last player that was spectated after switching to the freecam :/

**Comment by 42Firehawk** [comment]
if spec_mode or a derivative is available to read, it may be possible

**Comment by drweissbrot** [comment]
I may have done GSI dirty D: Had another look and (at least now) it looks like the game does indeed stop sending the player data, we're just not cleaning it up from the GSI state object properly -- whoops.

**Comment by ReneRebsdorf** [comment]
Awesome @drweissbrot this is a great fix 😊
