### ISSUE TITLE
Configuration option to keep icons of dead players on radar (the X) for x seconds or until the end of the round (whichever comes first)

### ISSUE THREAD

**Issue by ReneRebsdorf** [drweissbrot/cs-hud#106]
Hi,

The amount of time a death is marked on the radar is rather short, is there a way to extend this?
Preferably I would probably keep the markers until the next round starts, maybe both features are possible by setting the amount of time to a value higher than the round time, assuming it can reset on new round?

**Comment by drweissbrot** [comment]
the dead player icons disappearing was actually the result of a change to the game (cf. #92, #97)

should be solved in [v2.2.0](https://github.com/drweissbrot/cs-hud/releases/tag/v2.2.0), could you double-check you're using that version for all executables?

**Comment by ReneRebsdorf** [comment]
This is indeed resolved by updating, my bad.
