### ISSUE TITLE
Hide radar

### ISSUE THREAD

**Issue by Schadelbohrer** [drweissbrot/cs-hud#120]
Hi! Sorry if this is not the place to put this on, but I wanted to ask if there is the possibility to hide the radar to be able to use another one. I didn't find anything for it.

I think it could be a nice feature.

**Comment by drweissbrot** [comment]
Not an intentional feature, but you could try this: Inside your `userspace` directory, create a directory `radar`, and create an empty text file `radar.html`. Reload the HUD and it shouldn't be visible anymore.

**Comment by Schadelbohrer** [comment]
It worked like a charm. Thanks!
