### ISSUE TITLE
Loss bonus keeps on climbing

### ISSUE THREAD

**Issue by vladxy** [drweissbrot/cs-hud#124]
The team lost 7 rounds in a row and the loss bonus is now 5400$

https://i.imgur.com/3aUPvKk.png

**Comment by vladxy** [comment]
But when they win one back, it shows up normall, back down to 2900$

**Comment by drweissbrot** [comment]
Do you have a demo for this match by any chance?

**Comment by vladxy** [comment]
Should be able to see in this one, because Nexus got a lot of rounds in a row
https://www.challengermode.com/s/PGLCS2_EU/games/d1e829be-3028-43c4-083d-08dc1389e035
