### ISSUE TITLE
green screen, everything in right folder

### ISSUE THREAD

**Issue by andersontvcs2** [drweissbrot/cs-hud#126]

**Comment by drweissbrot** [comment]
From experience this usually happens because the `gamestate_integration_drweissbrot_hud.cfg` isn't in the right spot. To be clear, it should be inside the `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg` directory (unless you changed Steam's or the game's install location).  
There should be files like `boot.vcfg`, `gamemode_competitive.cfg`, and `user_keys_default.vcfg` in the same folder.

The file needs to be named exactly `gamestate_integration_drweissbrot_hud.cfg`; maybe there's a `.txt` in there?

The page will also just stay green as long as you're not either watching a demo, watching a live CSTV match, or on a map and in the spectators team. It may also stay green if the warmup hasn't started yet.


If none of that helps: Could you start a demo, open the HUD page in your browser, press `Ctrl`+`Shift`+`J`, then post a screenshot of the console window?

**Comment by ratatuel** [comment]
I have the same problem, my cs2 is located on D:/SteamLibrary, i dont have space enough to store it at C disk, i dont know what to do anymore, since it just doesnt work.

**Comment by drweissbrot** [comment]
> my cs2 is located on D:/SteamLibrary

In your case, the right directory should be `D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg`.

If it still doesn't work:
> Could you start a demo, open the HUD page in your browser, press `Ctrl`+`Shift`+`J`, then post a screenshot of the console window?

**Comment by MngkLrd** [comment]
Hi, same trouble
![image](https://github.com/drweissbrot/cs-hud/assets/123080755/d5c75a0d-3154-4784-bb6d-7696e5e94be3)
![image](https://github.com/drweissbrot/cs-hud/assets/123080755/68feab82-694f-429f-a35a-b10bf8550a24)
cs2 located on C:/

**Comment by drweissbrot** [comment]
@MngkLrd Looks like it's working as it should for you; the website in your browser can't actually show the game itself. I do see that that's not entirely obvious from the docs, thanks for pointing it out! :D
To get the game and the HUD in the same place, you need to use either an OBS browser source, or the separate overlay EXE, see https://github.com/drweissbrot/cs-hud/blob/c8f8a93574fe74eb756e46a2d7f6f16a692d4559/readme.md#obs-browser-source for OBS and https://github.com/drweissbrot/cs-hud/blob/c8f8a93574fe74eb756e46a2d7f6f16a692d4559/readme.md#fullscreen-windowed for the overlay app.

**Comment by MngkLrd** [comment]
@drweissbrot 
The "full screen in window" overlay method actually works well. But I think it would be useful to specify what should be run first:
1) CS2 + match
2) cs-hud-win
3) Electron (cs-hud.exe)
 Here is my result :)
![image](https://github.com/drweissbrot/cs-hud/assets/123080755/c3f43c3c-8ae4-4fdd-809b-b07e52ad8266)

It would be cool to add the ability to scale the radar via hud settings.

**Comment by drweissbrot** [comment]
Gonna close this one for now; if you're still having trouble, feel free to comment with a screenshot if you're still having trouble.

**Comment by andersontvcs2** [comment]
Hi, sorry for late response, let me grab you what i see

**Comment by andersontvcs2** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/bfbba928-f38a-422c-82bc-a37bc092b0e1)
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/488e546c-ebe4-4d0c-810f-4054a8b85ac5)
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/5aa3c263-e588-4852-9ced-ba51f1c95cb4)

**Comment by drweissbrot** [comment]
Ok, looks like it's mostly working for you now. The browser source probably needs to be a different size, and you'll need a Game Capture or so behind it, but I'm sure you can figure that out yourself :D
If this works for you (I personally just look at OBS while recording), you don't really need to do anything else.

If you want to overlay the HUD on top of the game, [follow the instructions under `Fullscreen Windowed` in the readme](https://github.com/drweissbrot/cs-hud/blob/bcecde36b9d08bfe1b32e995bcbcacd6c716ca4a/readme.md#fullscreen-windowed).

**Comment by andersontvcs2** [comment]
i have tried them all
wont work

**Comment by drweissbrot** [comment]
Not sure what you mean by "tried them all"?

**Comment by andersontvcs2** [comment]
game captuire, everything u suggested

**Comment by drweissbrot** [comment]
Ah, I see -- that sounds like an issue with OBS then. Don't think I can help you out with that, I don't know much about how their software works, sorry.

**Comment by andersontvcs2** [comment]
on obs what should the height etc be?

**Comment by andersontvcs2** [comment]
i have game capture on and its not being transparent

**Comment by drweissbrot** [comment]
> on obs what should the height etc be?

Width and height should be the same as the `Base (Canvas) Resolution`, as set under `File`, `Settings`, `Video`.

> i have game capture on and its not being transparent

The browser source needs to be on top of the game capture.
![image](https://github.com/drweissbrot/cs-hud/assets/11035385/d2aa1157-38f8-4fa2-a214-bfb21d4dfc24)
Make sure that in the browser source's properties, the `URL` is set to `http://localhost:31982/hud?transparent` and `Custom CSS` is completely empty.

**Comment by andersontvcs2** [comment]
that was the issue tysm, also one more thing, do u know how to remove all the ui's in the demo's?

**Comment by drweissbrot** [comment]
https://github.com/drweissbrot/cs-hud/blob/bcecde36b9d08bfe1b32e995bcbcacd6c716ca4a/docs/cvars.md#cl_draw_only_deathnotices
