### ISSUE TITLE
Resize Radar

### ISSUE THREAD

**Issue by trefsnider** [drweissbrot/cs-hud#127]
I'm trying to resize the radar to make it smaller by appending the .css file through my own theme. I created a folder inside the cs-hud directory that was created after installing the pre-packaged binaries. When I type in my theme's name into the config, the HUD throws me an internal server error and I have to reload with the default theme. I put a theme.json file in my theme's folder along with a separate radar folder that contains a radar.append.css text file changing 

img.radar-image {
	width: 100%;
}

to width: 50%. Do I need to create the .json and .css files in an IDE or am I not formatting and storing my files properly? Any help would greatly be appreciated and I'd also like to thank you for making this project to begin with, not to mention offering it for free.

**Comment by drweissbrot** [comment]
First of all, using `img.radar-image` will not work how you expect (things will not be positioned correctly), the CSS you'll want to use in `radar.append.css` is
```css
.radar {
    width: 50%; /* 50% is the default value */
}
```

This should be the directory structure:
```
cs-hud-win32.exe
cs-hud/
    userspace/
    your-theme-name/
        theme.json
        radar/
            radar.append.css
```

Your theme.json (`cs-hud/your-theme-name/theme.json`) needs to contain at least this:
```json
{
    "parent": "fennec"
}
```


If this doesn't help, could you check if there's anything in the console window after you get the Internal Server Error? Could you also post a ZIP or so of your theme folder?

**Comment by drweissbrot** [comment]
gonna close this one for now, if you're still having trouble, let me know
