### ISSUE TITLE
any way to use HUD overlay with CS xray?

### ISSUE THREAD

**Issue by easleyw13** [drweissbrot/cs-hud#128]
is it possible to use this hud but use the in-game xray to show team/equipment? as default every player is the same color regardless of team and you can't see their in-game name or equipment. 

let me know if this is possible or if i missed something in the customization/documentation.

thanks!

**Comment by drweissbrot** [comment]
Not entirely sure if this is what you're asking, but at least in CS:GO you could tell the game to show the little triangle, their name, and their equipment above players' heads using these commands in the in-game console:
```
cl_drawhud_force_teamid_overhead 1
cl_teamid_overhead_mode 2
```
Not sure if these commands still exist in CS2, or if they've been renamed or something.

**Comment by easleyw13** [comment]
force_teamid_overhead 1 worked perfectly. thanks again!
