### ISSUE TITLE
cs-hud.exe

### ISSUE THREAD

**Issue by pixe71** [drweissbrot/cs-hud#133]
I can't find cs-hud.exe in the folder
![Screenshot 2024-01-23 174722](https://github.com/drweissbrot/cs-hud/assets/52007751/36917e69-f566-4752-a7d0-8bd200b1879f)

**Comment by drweissbrot** [comment]
The binaries aren't in the source code or repository, they're only part of the [GitHub releases](https://github.com/drweissbrot/cs-hud/releases).

You should usually not have to build the binaries yourself.
If you really want to, the script to do it is in `build/build.sh`, but it probably only runs on Linux, not on Windows (but it might work in cygwin?).

For changing how things look, you can use the pre-existing binaries and just build a theme, cf. https://github.com/drweissbrot/cs-hud/blob/bcecde36b9d08bfe1b32e995bcbcacd6c716ca4a/docs/theming.md.

If you want to work on the HUD's source code (would be neat, I could use some help :D), you'll need to install [Node.js](https://nodejs.org/) and [Yarn](https://yarnpkg.com/getting-started/install) on your machine, then run `yarn watch`.
(I know this isn't ideal, I'll get around to writing docs about this and dockerizing the project eventually :D)

If none of this helped, let me know what you're hoping to do, maybe we can figure something out.
