### ISSUE TITLE
How can I take off the map table

### ISSUE THREAD

**Issue by HUGOM14** [drweissbrot/cs-hud#136]
How can I disable the bottom table that has the maps, I've been looking and the only thing I've found is to disable it when it's BO1

Here is an example of what I want to disable:
![Screenshot 2024-02-03 135517](https://github.com/drweissbrot/cs-hud/assets/158750025/a0f88d8f-2976-4c73-98b6-21c17db8b1e4)

**Comment by drweissbrot** [comment]
Should be possible [using a theme](https://github.com/drweissbrot/cs-hud/blob/1f9c2e22d381381dee627e10db8267b32abf7a6d/docs/theming.md): Set up a theme, in the theme's directory create a folder called `series-graph`, and inside that an empty text file called `series-graph.html` -- should do it :)
