### ISSUE TITLE
Hiding autokill coaches in overlay

### ISSUE THREAD

**Issue by AmjedAgabani** [drweissbrot/cs-hud#137]
Recently there's a new feature for coaching in CS2 where a coach is apart of the team and is auto-killed so they can spectate their team to coach

Is it possible to find a way to hide this auto-kill coach from the overlay so they don't show as a dead player permanently in the HUD?

Example below with coaches circled

![image](https://github.com/drweissbrot/cs-hud/assets/25209441/f3f3799d-6a04-4750-bdb5-f6f165890d4f)

**Comment by drweissbrot** [comment]
Could you post the link to a demo or Faceit match room with this issue?

**Comment by drweissbrot** [comment]
fixed in [v2.4.0](https://github.com/drweissbrot/cs-hud/releases/tag/v2.4.0); see [docs/hiding-players.md](https://github.com/drweissbrot/cs-hud/blob/1f9c2e22d381381dee627e10db8267b32abf7a6d/docs/hiding-players.md) for instructions
