### ISSUE TITLE
Focused Player image

### ISSUE THREAD

**Issue by chaz1to** [drweissbrot/cs-hud#138]
Is there a way to add specific images for the "focused player" in the HUD?

**Comment by drweissbrot** [comment]
Do you mean like an avatar or a facecam? Not currently, but hoping to add this feature eventually, cf. #109.

Let me know if you meant something else :D

**Comment by chaz1to** [comment]
I was referring more to the fact that in the same way that there is a "team-logos" folder, you can do the same thing for player avatars. For example, you could download the PNG images from HLTV to a specific folder called "player-avatars". The PNG files could be named using the same names as the ones previously set in the "player name overrides". For instance, if I associate tabsen's SteamID with the name "tabsen" in "player-name-overrides", I could download tabsen's image from HLTV, name it tabsen.png, and put it in the "player-avatars" folder. The software should then be able to detect the similarity between the player's name and the image's name.

**Comment by drweissbrot** [comment]
Yeah, that's what I meant :D Not a feature currently, but should eventually be added as part of #109.
