### ISSUE TITLE
Map displacements

### ISSUE THREAD

**Issue by borzaka** [drweissbrot/cs-hud#141]
Map: `de_ancient`

- The CTs are not in the spawn area.
![image](https://github.com/drweissbrot/cs-hud/assets/1230402/127fae19-28f2-4244-96bf-ceae19134093)
- Molotovs are displaced.
![image](https://github.com/drweissbrot/cs-hud/assets/1230402/a76bc270-32d9-4c85-8390-5abfa5235bb6)

**Comment by 42Firehawk** [comment]
The radar files currently used are the final versions of simpleradar available. Currently replacement radars are, at the simplest, hard to use (issue is known separately though)

**Comment by 42Firehawk** [comment]
#115

**Comment by 42Firehawk** [comment]
For the molotov displacement, do you have a demo and a round (preferably with timestamp) of the screenshot? Makes it much faster to reproduce and find the cause

**Comment by AmjedAgabani** [comment]
> For the molotov displacement, do you have a demo and a round (preferably with timestamp) of the screenshot? Makes it much faster to reproduce and find the cause

Just finished a cast where this happens, here's an example 

https://beta.faceit.com/en/cs2/room/1-83c65a54-184c-49e9-9036-81c4ca683f31
Round 9, molotov thrown from red to alley.

Here's a timestamped Twitch VOD of the issue : https://www.twitch.tv/videos/2054231183?t=00h28m39s

**Comment by borzaka** [comment]
> For the molotov displacement, do you have a demo and a round (preferably with timestamp) of the screenshot? Makes it much faster to reproduce and find the cause

Yesterday we had a tournament, I have a demo for you: https://drive.google.com/file/d/1JiWolXgkRjCT3o1NnbCq0Yl1QDOdx0u9/view?usp=drive_link
- 2nd round, Ts attacking B (around 3:00 in the demo)
- 4th round, Ts attacking B (around 5:24 in the demo)
- probably many more rounds worth watching where molotovs used
