### ISSUE TITLE
Add option to disable the radar

### ISSUE THREAD

**Issue by borzaka** [drweissbrot/cs-hud#142]
The current radar imlementation has issues: #141 
I would like to use the native CS2's radar. An option in the settings would be nice.

Console commands needed for this:
```
cl_draw_only_deathnotices 1
cl_obs_interp_enable 0
cl_drawhud_force_teamid_overhead 1
cl_teamid_overhead_always 2
cl_drawhud_force_radar 1
```

The `cl_drawhud_force_radar 1` is the important one.

**Comment by drweissbrot** [comment]
I think I'd rather spend time on finding a solution to the radar issues themselves (#113).
Under normal circumstances this would be too niche of a use case for official support in my opinion, so it should be handled via a theme. See https://github.com/drweissbrot/cs-hud/issues/120#issuecomment-1887734612 for instructions.
