### ISSUE TITLE
Add option to modify the radar icon sizes

### ISSUE THREAD

**Issue by AmjedAgabani** [drweissbrot/cs-hud#143]
Would be nice to be able to change the radar icon size on the HUD standalone from changing the entire HUD scaling

**Comment by drweissbrot** [comment]
Too niche of a use case for first class support in my opinion. [You can do this with a theme](https://github.com/drweissbrot/cs-hud/blob/1f9c2e22d381381dee627e10db8267b32abf7a6d/docs/theming.md), though I did notice that the radar icon sizes aren't CSS variables, which makes them a bit more effort to modify than should be the case (tracking in #146).

Thanks for the suggestion though! :)
