### ISSUE TITLE
HUD overlaps the scoreboard during freezetime at default settings

### ISSUE THREAD

**Issue by AmjedAgabani** [drweissbrot/cs-hud#144]
HUD is overlapping the scoreboard during freeze time as shown below.

![image](https://github.com/drweissbrot/cs-hud/assets/25209441/a1684d8d-48e5-4a6f-b966-05cd5715a308)

I have to change `css.base-scale-factor` to 8px, which would be fine however that leads to the icon sizes being too small for my tastes and I can't modify that as referenced in this issue https://github.com/drweissbrot/cs-hud/issues/143

**Comment by 42Firehawk** [comment]
This would be easiest to accomplish with a custom override theme which force changes just the values you'd want to increase again, see [theming docs](docs/theming.md)

**Comment by drweissbrot** [comment]
As 42Firehawk said, you can do what you want with a theme.
Easiest solution would be to disable the K/A/D/ADR boxes, which you can do by creating the directories `your-theme-name/sidebars/sidebar/player/additional-stats` (i.e. each directory is nested in its parent), and in the `additional-stats` directory, creating an empty text file called `additional-stats.html`.

If you want to keep the boxes, that'd require a lot of tricky spacing adjustments. You can still do that with a theme, but I don't see why you'd show the scoreboard at all (feel free to let me know :D), so won't spend time on finding out :D
