### ISSUE TITLE
Only green screen 

### ISSUE THREAD

**Issue by maxvita2006** [drweissbrot/cs-hud#148]
Hi, when I install everything like in the instruction I have only green screen on http://localhost:31982/hud

**Comment by drweissbrot** [comment]
Will close this one for now, feel free to reopen with the data from above if you're still having trouble.

**Comment by maxvita2006** [comment]
Now is working! Thx <33 
Btw it is save to play cs2 normal with this csf in game?

**Comment by drweissbrot** [comment]
yes, it's safe
