### ISSUE TITLE
language?

### ISSUE THREAD

**Issue by ajz4k** [drweissbrot/cs-hud#149]
where can i change language or texts like "players alive"?

**Comment by drweissbrot** [comment]
You can currently do this by [creating a theme](https://github.com/drweissbrot/cs-hud/blob/1f9c2e22d381381dee627e10db8267b32abf7a6d/docs/theming.md); specifically by copying the respective `.html` file that contains the text you'd like to replace into your theme and updating the text in there.

Hoping to eventually make this easier (tracked in #118).
