### ISSUE TITLE
overlay images (e.g. for sponsors) 

### ISSUE THREAD

**Issue by ajz4k** [drweissbrot/cs-hud#150]
what about overlay images (e.g. for sponsors)?

**Comment by drweissbrot** [comment]
see https://github.com/drweissbrot/cs-hud/blob/1f9c2e22d381381dee627e10db8267b32abf7a6d/docs/overlay-images.md

**Comment by ajz4k** [comment]
hm, ok and there is "Note that animations (for transitions between multiple sponsors, for instance) are possible using all three of these formats." how i can make transitions in png images?

**Comment by drweissbrot** [comment]
I'd go for WebP instead of PNG, which should be easy enough to create with GIMP for example (see https://www.reddit.com/r/GIMP/comments/h0gg1j/comment/ftlyo10).

If you have to use PNGs, ask your favorite search engine for `create animated png` :D
