### ISSUE TITLE
Phantom dead players appear on the HUD

### ISSUE THREAD

**Issue by borzaka** [drweissbrot/cs-hud#151]
Reproduce:
- Have a match with `mp_disconnect_kills_players 0`
- Some players start to disconnect before the game ends (lost cause scenario, where the team can't win and last round)
- Have another match with different players (and even on a different map) on the same server right after.
- The early disconnected players from the prev match still appear on the HUD as dead players.

Solutions:
- Full game server restart after every match.
- The HUD filter players.

I know about the hide players feature, but these phantom players don't have a steamId, and/or sometimes they just don't use typeable characters.

The `status` command shows this on the server. Maybe it helps to filter out phantom players from the HUD:
```
[Client] ---------players--------
[Client]   id     time ping loss      state   rate name
[Client]    0  1:34:20    0    0     active 786432 '[ESM] Attila'
[Client] 65535 [NoChan]    0    0 challenging      0 ''
[Client]  258    13:40    0    0     active 1000000 'strong3r'
[Client] 65535 [NoChan]    0    0 challenging      0 ''
[Client] 65535 [NoChan]    0    0 challenging      0 ''
[Client]    5      BOT    0    0     active      0 'CSTV #1'
[Client]    6    17:15    0    0     active 1000000 'NonS3nS-'
[Client]    7    17:10    0    0     active 786432 '-LANCER'
[Client]    8    17:06    0    0     active 786432 'gabcimanô'
[Client]    9    16:52    0    0     active 786432 'James8K'
[Client]   10    16:47    0    0     active 786432 'FL'
[Client]   11    16:31    0    0     active 1000000 'sc0rchzz'
[Client]   12    16:05    0    0     active 786432 'boo'
[Client]   13    01:55    0    0     active 786432 'xelex..'
[Client]   14    14:10    0    0     active 1000000 'makszi'
```

Demo file: https://drive.google.com/file/d/1cfOre_NjMoM8v1YYTVWAH-xC-mIz_7w6/view?usp=drive_link

![image](https://github.com/drweissbrot/cs-hud/assets/1230402/bcc41db1-412e-435c-9e50-4f2c9e46b40a)

![image](https://github.com/drweissbrot/cs-hud/assets/1230402/8fd2850c-1550-4bc7-b9ec-0fd001a3cfa4)

**Comment by borzaka** [comment]
I'am still experiencing this issue. I still have a dead player on the HUD.
I had to hide manually on the config page.

```
---------players--------
  id     time ping loss      state   rate adr name
65535 [NoChan]    0    0 challenging      0unknown ''
```

**Comment by drweissbrot** [comment]
As always, I need a demo :D

**Comment by borzaka** [comment]
Sure @drweissbrot, here it is: https://esm-public-images.s3.eu-central-1.amazonaws.com/esm_1714249619792_2024-04-13_10-35-00_5_de_inferno_PewPewPandas_vs_LEGO.dem.zip
