### ISSUE TITLE
I can´t change te name of the second team 

### ISSUE THREAD

**Issue by NoHands67** [drweissbrot/cs-hud#153]
I can't change the name of the second team on the HUD, I've tried everything, I've read through each of the .txt files in the archive and still haven't found a solution, I need help. I attach screenshots of what happened
![imagen_2024-02-27_104924047](https://github.com/drweissbrot/cs-hud/assets/161476470/dceec96f-4fe9-4ce5-8a4f-792836d6922f)

![imagen_2024-02-27_104905175](https://github.com/drweissbrot/cs-hud/assets/161476470/c0a21dd3-5ed4-4dd1-ae81-14627abb5553)

**Comment by drweissbrot** [comment]
I think you just need to put everything into the upper text box?  
The lower text box (`teams.playerNameOverrides`) is used to change the name of a single player -- so currently, you're setting the name of the player with Steam ID `76561198294623066` to `LCDTM`.

**Comment by NoHands67** [comment]
tks!!! I will prove that

Thank u so much bro!

**Comment by NoHands67** [comment]
Bro, what you suggested in the previous email worked for me, but now I
can't seem to place the team logos. I might still be doing something wrong

Is there any specific order for placing everything in the text-box?

[image: image.png]

**Comment by drweissbrot** [comment]
The team logo image files must be named exactly like the team name after overrides, followed by `.png`.

So, assuming you got `76561198294623066 LCDTM` in `teams.teamNameOverrides`, the file must be named `LCDTM.png`. This is case-sensitive, so `LCDTM.PNG` will not work.

**Comment by NoHands67** [comment]
Oh, okay, only in lowercase, it doesn't accept uppercase. I will prove that
