### ISSUE TITLE
How i change the color of player's money, or fix Chroma Key bug

### ISSUE THREAD

**Issue by jmmonteir0** [drweissbrot/cs-hud#154]
When I remove the green background from Hud, some things that are green also disappear along with the background, do you know how to fix it?

![Screenshot_3](https://github.com/drweissbrot/cs-hud/assets/118014624/3bed90e5-9818-4f93-96cb-4b8fb09a6fa5)

**Comment by drweissbrot** [comment]
please see https://github.com/drweissbrot/cs-hud/issues/134#issuecomment-1914123238

**Comment by jmmonteir0** [comment]
Thanks for fast reply <3 you saved my life
