### ISSUE TITLE
How to use the not-pre-package version

### ISSUE THREAD

**Issue by Choquinn** [drweissbrot/cs-hud#160]
i want to modify the archives for a custom HUD, but i don't know how to use it in code version(not executable)

**Comment by drweissbrot** [comment]
You probably don't need to do that :D Pretty much everything about how the HUD looks can be modified by [creating a theme](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/docs/theming.md) (themes work just fine with the pre-built binaries).

If you actually do want to customize the inner workings, you'll need to install [Node.js](https://nodejs.org/) and [Yarn](https://yarnpkg.com/getting-started/install) on your machine, then run `yarn watch`. (I know this isn't ideal, I'll get around to writing docs about this and dockerizing the project eventually :D)
