### ISSUE TITLE
Hud not working Green Screen

### ISSUE THREAD

**Issue by bkwhat** [drweissbrot/cs-hud#163]
hud not showing up anymore, shows greenscreen only now on the local host link. worked prior to most recent cs2 update

**Comment by jntm7** [comment]
+1 doesn't work for me either as per the latest update

**Comment by drweissbrot** [comment]
Everything is still working fine on my end (at least after [the 2024-03-19 update](https://steamdb.info/patchnotes/13791849/)).

If you're still seeing issues:
Please post a screenshot of the console window (the one with the text `CS HUD active at http://127.0.0.1:31982. Press Ctrl+C to quit.`)
Please also open up http://127.0.0.1:31982, press `Ctrl+Shift+J`, select the `Console` tab, and post a screenshot of that too.

**Comment by jntm7** [comment]
Nevermind, it's working fine for me now, a mistake on my part had it returning a blank greenscreen. Excellent work! :)

**Comment by bkwhat** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/60736151/2db60505-0df2-4067-a33a-0a8fd618bbca)
![image (1)](https://github.com/drweissbrot/cs-hud/assets/60736151/052a9ea0-6e36-4d50-84da-1f8aeaf0103c)

Hello attached.

**Comment by bkwhat** [comment]
![hud](https://github.com/drweissbrot/cs-hud/assets/60736151/f8b3f6e8-f8c0-46d9-9d03-839e03efcf80)

**Comment by MaxGame1760** [comment]
How you fix this?
