### ISSUE TITLE
Hud is not applied over the game

### ISSUE THREAD

**Issue by shre1k** [drweissbrot/cs-hud#164]
Good afternoon The hud does not apply over the game. I don’t understand why this is so, although I do everything according to the instructions

**Comment by drweissbrot** [comment]
What do you see when you visit http://127.0.0.1:31982 in your browser? (Make sure you open CS and spectate CSTV in some way, e.g. watching a demo).

**Comment by drweissbrot** [comment]
gonna close this one for now, if you're still having trouble, let me know
