### ISSUE TITLE
What is the desired W x H to make this not all; cluttered up 

### ISSUE THREAD

**Issue by andersontvcs2** [drweissbrot/cs-hud#170]
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/56b71df8-d5a8-4963-93bb-841e1e3c2b21)

**Comment by drweissbrot** [comment]
Usually it should work on everything that's roughly a 16:9 aspect ratio (e.g. 1280x720, 1920x1080, 2560x1440, 3840x2160).

May be different if you changed `css.base-scale-factor` on the config page, or if you're using a custom theme.

**Comment by andersontvcs2** [comment]
I did not change anything on config page

**Comment by drweissbrot** [comment]
The game's resolution doesn't matter. You're using a browser source in OBS, right? The browser source needs to be set to one of the resolutions I mentioned above, as does the `Base (Canvas) Resolution` in OBS's video settings.

**Comment by andersontvcs2** [comment]
I am using Obs

**Comment by andersontvcs2** [comment]
I will check settings now

**Comment by andersontvcs2** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/9f58f74e-3384-4926-819d-72490f6ac111)

**Comment by drweissbrot** [comment]
> The browser source needs to be set to one of the resolutions I mentioned above

check this too please, and/or post a screenshot of the entire OBS preview

**Comment by andersontvcs2** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/e1a45f9e-ffe8-430f-ad5f-6184dc171832)

**Comment by andersontvcs2** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/156965837/949d1c3d-2213-4317-8c13-bddabddd2bf8)

**Comment by andersontvcs2** [comment]
Seems fixed, I have fixed my Width and Height

**Comment by 42Firehawk** [comment]
As a note on future fixes, this is most likely a result of the default width and height within the OBS browser source being set at 800x600, and sometimes doesn't detect the desired resolution properly, so with some other applications designed for browser source it's a necessary part of config
