### ISSUE TITLE
Hud showing but no image from the cs2 game.

### ISSUE THREAD

**Issue by hlyl** [drweissbrot/cs-hud#172]
Super cool project and great work... fits a sweet spot for me on making tournaments at my work-place... thanks a lot
OS: win 11
Browser: Edge
Watching the game and running the cs-hud-win.exe shows CMD window that CS HUD is active at  http://127.0.0.1:31982.
Config loads
Hud opens and does show the graphics and does also show the correct player name etc, but the feed from the game is Green:
![image](https://github.com/drweissbrot/cs-hud/assets/1834987/283483d4-ec32-4f84-a22a-fd6203aacc23)
In reference to other issue, have checked and confirmed that the file: `gamestate_integration_drweissbrot_hud.cfg`
is in the correct path: `C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\game\csgo\cfg`
Please help me understand if further information make it easier for you to identify the root of the issue :)

**Comment by drweissbrot** [comment]
The HUD can't get the game's footage; if you use it in the browser, it'll always have the green background. To get the HUD overlayed on top of the game, you need to use either an OBS browser source or the separate overlay EXE to put the HUD on top of your game client in Fullscreen Windowed mode ([both methods are described in the readme](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/readme.md#obs-browser-source)).

You're not the first one to ask this, so probably means it should be clearer in the readme :D

(Or, if running straight in the browser is important to you, I think you can probably implement it using the [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API)? Won't do it myself, but if you end up doing this, please submit a PR :D)
