### ISSUE TITLE
Assists stat counting flash assists as well

### ISSUE THREAD

**Issue by borzaka** [drweissbrot/cs-hud#173]
During frezzetime: Kill, Assist, Death and ADR stats are displayed.
It looks like the assists is counting flash assists as well, otherwise the 500 ADR wouldn't be possible in this case after the first round.
I thinks it's a little bit confusing.

![image](https://github.com/drweissbrot/cs-hud/assets/1230402/5f019287-8184-42de-bdb8-42ad9cfeb040)

**Comment by patrekurlol** [comment]
Its taken from the game statistics, flash assists count as assists there

**Comment by borzaka** [comment]
The native scoreboard displays them desperately.
I expected the same data here as well.

**Comment by Zel1xa** [comment]
enemy flashed ≠ flash assist, this is not a bug.

**Comment by ReneRebsdorf** [comment]
> enemy flashed ≠ flash assist, this is not a bug.

Because they are not the same as you say, it is a bug that it counts the 2 assists in the screenshot for 'vincso', since there is no room for kill assists if noLen got the total of 500 dmg based on the ADR stat for the first round.

**Comment by Zel1xa** [comment]
> > enemy flashed ≠ flash assist, this is not a bug.
> 
> Because they are not the same as you say, it is a bug that it counts the 2 assists in the screenshot for 'vincso', since there is no room for kill assists if noLen got the total of 500 dmg based on the ADR stat for the first round.

Flash Assist counts as an assist, it comes from GSI, it cannot be fixed. because this is not a bug, this is how it should be

**Comment by ReneRebsdorf** [comment]
> > > enemy flashed ≠ flash assist, this is not a bug.
> > 
> > 
> > Because they are not the same as you say, it is a bug that it counts the 2 assists in the screenshot for 'vincso', since there is no room for kill assists if noLen got the total of 500 dmg based on the ADR stat for the first round.
> 
> Flash Assist counts as an assist, it comes from GSI, it cannot be fixed. because this is not a bug, this is how it should be

Ah, I get you now.

**Comment by drweissbrot** [comment]
The game does indeed count flash assists in the Assists column of the scoreboard. Bit weird if you ask me (especially since I don't think they ever mentioned it in the changelogs?), but if the game does it this way, the HUD probably should do the same.
