### ISSUE TITLE
Config not showing when packaged

### ISSUE THREAD

**Issue by FranTheNegro** [drweissbrot/cs-hud#174]
I package with pkg cs-hud.js, when i run the cs-hud-win.exe the config page show this 
![image](https://github.com/drweissbrot/cs-hud/assets/85368445/bc022103-bf2e-43ee-b81d-c84c4ea71d93)
also the hud not work, I added it through scripts and assets as it says, but I still can't package it correctly to make it work.

**Comment by FranTheNegro** [comment]
i guess that a packaged in the wrong way, i'm newbie programmer lol

**Comment by drweissbrot** [comment]
Is there a reason you're packaging the binary yourself? Unless you're making changes to the server side you shouldn't have to, all visual changes can be made via theming.

I'd assume the error is because you're doing it on Windows, I've only ever run the packaging script on Linux :D

**Comment by drweissbrot** [comment]
gonna close this one for now, feel free to reopen if you're still having trouble
