### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by 4nd1Tr4sh** [drweissbrot/cs-hud#175]
The hood is applied on CS2, I have sound and I can control the camera, but the hood is applied along with a black background. There is no way to remove it.
![Screenshot 2024-04-26 154625](https://github.com/drweissbrot/cs-hud/assets/168177249/95144d9e-e2a3-495d-a139-e569f662edbb)
![Screenshot 2024-04-26 154528](https://github.com/drweissbrot/cs-hud/assets/168177249/b978f3f4-6c3f-42a7-89bc-3e0d496f61e8)

**Comment by Choquinn** [comment]
try to change the background color in the css

**Comment by cmaalaa** [comment]
estou tendo o mesmo problema de tela preta na HUD, poderia me auxiliar em como resolver?

**Comment by drweissbrot** [comment]
Please don't use chroma keying, it'll look horrible if you do :D

If you're still seeing this: Are you using the [OBS browser source](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/readme.md#obs-browser-source) approach? If so, make sure you're using the URL exactly as in the readme (including the `?transparent`), and that `Custom CSS` is empty.

**Comment by sykes6669** [comment]
Try to disable FXAA anti-aliasing in NVIDIA control panel
it helped for me

**Comment by 4nd1Tr4sh** [comment]
> Please don't use chroma keying, it'll look horrible if you do :D
> 
> If you're still seeing this: Are you using the [OBS browser source](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/readme.md#obs-browser-source) approach? If so, make sure you're using the URL exactly as in the readme (including the `?transparent`), and that `Custom CSS` is empty.

Thanks everyone for your help. Let me clarify that the version for OBS worked, I couldn’t exactly display thin on my screen. Using magic, start it after a while, everything fixed itself.
