### ISSUE TITLE
Add Player Images

### ISSUE THREAD

**Issue by HUGOM14** [drweissbrot/cs-hud#176]
Can you make an update to activate a function to put a player image to appear in the focused player set?
I don't know if that is possible to do but it would completely change the HUD in a positive way.

I've used your home page photo to make an example of what I'm talking.

![exemplo](https://github.com/drweissbrot/cs-hud/assets/158750025/f8d0e2fe-354f-4224-b1a7-ce196d294921)

**Comment by drweissbrot** [comment]
not something you can do natively right now, but something I'd like to add eventually -- already tracked in #109

**Comment by GooDy06** [comment]
> це не те, що ви можете зробити прямо зараз, але те, що я хочу додати зрештою - це вже відстежено в #109

Just a great idea to look forward to! As well as adding webcams if possible. Thanks for such a great hud
