### ISSUE TITLE
C4 color change on radar & Radar resize

### ISSUE THREAD

**Issue by jackweasley** [drweissbrot/cs-hud#177]
I feel like the C4 hardly to notice in the radar when it drops on the map and another adjustment I would like to ask are we able to change the size of the radar?

**Comment by drweissbrot** [comment]
see #127 for resizing the minimap

I think changing the dropped bomb's color currently can't be done the "proper" way (at least not easily), but you could edit [the bomb icon SVG file](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/src/themes/fennec/img/icons/radar/dropped-bomb.svg), change its color, [then create a theme and override the icon file](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/docs/theming.md#overriding-files).

**Comment by drweissbrot** [comment]
gonna close this one for now, feel free to reopen if you're still having trouble
