### ISSUE TITLE
MVP ROUND PLAYER

### ISSUE THREAD

**Issue by GooDy06** [drweissbrot/cs-hud#178]
Will it be possible to add a player of the round when the round ends on the screen? example added
![image](https://github.com/drweissbrot/cs-hud/assets/59780005/1b1eeba3-ed5d-4f65-ac32-c53f0a59cc9b)

**Comment by drweissbrot** [comment]
I'm not sure if we get this from the game via Game State Integration. Even if we do, to be honest, I don't think I want this personally, so I'll probably not spend time on this.

If someone else wants to implement it, feel free to send a PR :D
