### ISSUE TITLE
New to HUD programming

### ISSUE THREAD

**Issue by JeffYen95** [drweissbrot/cs-hud#179]
Hi there,

I know this is a stupid question, but I'm not a programmer. May I know which software do I need to install to edit/modify the theme? I did downloaded the source code.zip but it doesn't change anything to the HUD if I done any changes on it. I read through the whole theming.md but I still don't understand how to create a theme or modify.

Much appreciate if I really learn something on this.

Thanks.

**Comment by drweissbrot** [comment]
In terms of software, you only need a text editor, like Windows' Notepad (not Word or Wordpad or anything like that though).

You don't need the source code ZIP to create a theme; all theme files, i.e. [the entire fennec directory](https://github.com/drweissbrot/cs-hud/tree/a88f3d57aca662489ee5c33e33285e695ed6a83d/src/themes/fennec), are embedded in `cs-hud-win.exe`/`cs-hud-linux`.  
You need to create a folder in the `cs-hud` directory that gets created next to `cs-hud-win.exe` when you run the HUD for the first time (e.g. `cs-hud/my-theme`). Inside of that directory, you can override files from the `fennec` directory by just creating them (or append by creating a `.append.` file), e.g. `cs-hud/my-theme/css/vars/colors.append.css`.

Does that help?

**Comment by drweissbrot** [comment]
gonna close this one for now, feel free to reopen if you're still having trouble
