### ISSUE TITLE
Changing color of nickname

### ISSUE THREAD

**Issue by pawelmeszynski** [drweissbrot/cs-hud#183]
Is it possible to change a color of nicknames on hud? css.terrorists-text-rgb only changing the small part (letters K from kills, and D from deads).

**Comment by drweissbrot** [comment]
I don't think there's a CSS variable for it currently. You could create a `sidebars/sidebar/player/name/name.append.css` file in your theme with these contents:
```css
.name {
    color: #ff69b4;
}
```

If you want different colors depending on if they're CT or T, I think you may need to override `sidebars/sidebar/player/name/name.js`, [import its parent](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/docs/theming.md#import-files-from-a-parent-theme-javascript), include the computed `colorClass` property ([like here](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/src/themes/fennec/sidebars/sidebar/player/kills/kills.js#L14-L18)), then override `sidebars/sidebar/player/name/name.html` too and add `colorClass` as another class [in this line](https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/src/themes/fennec/sidebars/sidebar/player/name/name.html#L1).

**Comment by drweissbrot** [comment]
Gonna close this one, feel free to reopen if you're still having trouble.
