### ISSUE TITLE
I have an HUD can I use it with your gamestate_integration?

### ISSUE THREAD

**Issue by HUGOM14** [drweissbrot/cs-hud#185]
Hi!
I have a custom CS2 HUD. I have it as ZIP folder and is currently working with Lexogrine HUD manager but I'm not interested of paying 35€ per month to use it.
I'm I able to use that HUD with your gamestate integration?

**Comment by drweissbrot** [comment]
Probably not without making a lot of changes to it. I have never used their software but I'd assume it works entirely differently.
