### ISSUE TITLE
Animations using overlay images

### ISSUE THREAD

**Issue by keczua** [drweissbrot/cs-hud#186]
Hello,

How to create an animations using overlay-images folder located in cs-hud/userspace? I can upload one image to HUD but I don't know how to make 2 images that will change from one to another during the match

**Comment by drweissbrot** [comment]
The HUD does not support this by itself. If you want to have an animation, you need to use [an animated image](https://github.com/drweissbrot/cs-hud/issues/150#issuecomment-1964361958).

**Comment by keczua** [comment]
Thank you for the answer :)
