### ISSUE TITLE
hud not working

### ISSUE THREAD

**Issue by iltozz** [drweissbrot/cs-hud#189]
i did everything but the hud didnt worked please help

**Comment by drweissbrot** [comment]
I can't help you based on this. What exactly is not working (screenshots/videos if possible), how exactly are you using the HUD (browser source), etc.?

**Comment by iltozz** [comment]
> I can't help you based on this. What exactly is not working (screenshots/videos if possible), how exactly are you using the HUD (browser source), etc.?

im just starting the .exe file and nothing is happening and the browser link is not working or i just dont understand somethin
![image](https://github.com/user-attachments/assets/466ce1a1-d4a1-41a8-a7e5-8d1aef793eaf)

**Comment by drweissbrot** [comment]
You always need to run `cs-hud-win.exe` (it'll show up as a command prompt window).

If you want to use the overlay, you additionally need to run `cs-hud.exe`.

**Comment by iltozz** [comment]
> You always need to run `cs-hud-win.exe` (it'll show up as a command prompt window).
> 
> If you want to use the overlay, you additionally need to run `cs-hud.exe`.

its saying that this is virus lol

**Comment by iltozz** [comment]
> > You always need to run `cs-hud-win.exe` (it'll show up as a command prompt window).
> > If you want to use the overlay, you additionally need to run `cs-hud.exe`.
> 
virustotal and win defender are saying that this is virus lol

**Comment by iltozz** [comment]
> are you sure you downloade the right file? [virustotal is telling me 1/73 :D](https://www.virustotal.com/gui/file/b7ec0810ffba236b0bf9c566f0ff025a7c23fc76a09cd7d196c0e2b8b696d4fe)

https://i.imgur.com/3TqO1MW.png

**Comment by drweissbrot** [comment]
Yeah, that looks identical to my result -- if only one of their scanners thinks it's malware, that's probably a false positive :D

If you don't want to trust it, you could try to manually run the code via node. I can't walk you through that though.

**Comment by iltozz** [comment]
https://i.imgur.com/S7r3eSK.jpeg

> Yeah, that looks identical to my result -- if only one of their scanners thinks it's malware, that's probably a false positive :D
> 
> If you don't want to trust it, you could try to manually run the code via node. I can't walk you through that though.

https://i.imgur.com/S7r3eSK.jpeg wtf

**Comment by iltozz** [comment]
> https://i.imgur.com/S7r3eSK.jpeg
> 
> > Yeah, that looks identical to my result -- if only one of their scanners thinks it's malware, that's probably a false positive :D
> > If you don't want to trust it, you could try to manually run the code via node. I can't walk you through that though.
> 
> https://i.imgur.com/S7r3eSK.jpeg wtf

i think i have fixed it, thanks for ur help

**Comment by iltozz** [comment]
> Yeah, that looks identical to my result -- if only one of their scanners thinks it's malware, that's probably a false positive :D
> 
> If you don't want to trust it, you could try to manually run the code via node. I can't walk you through that though.

how to make it like that so i can see the hud in the game?

**Comment by drweissbrot** [comment]
> how to make it like that so i can see the hud in the game?

https://github.com/drweissbrot/cs-hud/blob/a88f3d57aca662489ee5c33e33285e695ed6a83d/readme.md#fullscreen-windowed
