### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by CRISMinoso** [drweissbrot/cs-hud#193]
- Add images of the players next to the name

- Add a fire effect next to the name of the team that won "x" number of rounds

I highlighted the examples in green in the following image, but the player's photo could be in the middle of the hud:

![image](https://github.com/user-attachments/assets/21e28c87-8b07-44f3-a6d9-59774646397e)

**Comment by drweissbrot** [comment]
player avatars are tracked in #109 

I'm not interested in the fire thing, so I won't build that. Feel free to add it to a custom theme, or submit a PR to add it to the default theme.
