### ISSUE TITLE
Green Screen Issue

### ISSUE THREAD

**Issue by PabloEstebean** [drweissbrot/cs-hud#196]
I've seen others with the same issue as this, but most solve it without answering how they did so. I've followed the guide, placing the gamestate_integration_drweissbrot_hud.cfg in the Counter-Strike Global Offensive/csgo/cfg folder.

![image](https://github.com/user-attachments/assets/a87e2013-f6f9-4fe3-883a-226647d3a667)

I then ran the cs-hud-win.exe once I was in a practice match in the spectator team. 

![image](https://github.com/user-attachments/assets/eb3f7fe4-44b5-4390-b3d2-60e160d4c3d2)

But when I open the link, I get the config screen all set up and good, but clicking the HUD icon gives me a green screen. As well as that, the Radar just gives me a grey screen. 

![image](https://github.com/user-attachments/assets/c927ac8f-96c7-476d-907f-21ed6cc8d21c)
![image](https://github.com/user-attachments/assets/85f979d7-1ff6-4c30-9c36-4f137317846c)

Any help would be appreciated!

**Comment by 42Firehawk** [comment]
the cfg should be under Counter-Strike Global Offensive/game/csgo/cfg

**Comment by PabloEstebean** [comment]
> the cfg should be under Counter-Strike Global Offensive/game/csgo/cfg

My screenshot shows it is in there.

**Comment by 42Firehawk** [comment]
that is the Counter-Strike Global Offensive/csgo/cfg directory, not Counter-Strike Global Offensive/game/csgo/cfg
the Counter-Strike Global Offensive/csgo/cfg directory is the csgo install, not the CS2 install.

**Comment by PabloEstebean** [comment]
> that is the Counter-Strike Global Offensive/csgo/cfg directory, not Counter-Strike Global Offensive/game/csgo/cfg the Counter-Strike Global Offensive/csgo/cfg directory is the csgo install, not the CS2 install.

Thank you so much! That was the solution!!

**Comment by PabloEstebean** [comment]
This was solved by putting it in the correct folder as 42Firehawk said.
