### ISSUE TITLE
Not showing who won the map

### ISSUE THREAD

**Issue by dthbaron** [drweissbrot/cs-hud#197]
Even after setting all maps and setting the team names, when i type the team name into who won map 1 under the score of map it shows both teams with checked boxes rather than the winner of last map when its the 3rd map s
![image](https://github.com/user-attachments/assets/86bf16c8-5c33-43c1-9d48-44f715df1f85)

**Comment by drweissbrot** [comment]
The team name in `series.maps.1.pickTeam` etc. must exactly match the name that is displayed in the HUD, so in this case it would be e.g. `Counter-Terrorists` (it's case sensitive).

**Comment by dthbaron** [comment]
> The team name in `series.maps.1.pickTeam` etc. must exactly match the name that is displayed in the HUD, so in this case it would be e.g. `Counter-Terrorists` (it's case sensitive).

And how to change displayed in hud name?

**Comment by drweissbrot** [comment]
https://github.com/drweissbrot/cs-hud/blob/5214cd72e879d464b21d7286b13618edf6936a19/docs/team-name-overrides.md
