### ISSUE TITLE
HUD Not Showing

### ISSUE THREAD

**Issue by MordredXYZ** [drweissbrot/cs-hud#78]
Yo!

I've set up the HUD as per the installation instructions, placed the integration file properly and I'm using version 2.1, however I don't see the HUD or radar.

![image](https://github.com/drweissbrot/cs-hud/assets/99334199/8fbd9832-a78e-4876-82ea-3734d2a54a57)

I've placed the integration file, opened CS2, connected to a local server in the spectator slot with 2 bots in it, and I don't see a HUD or radar.

What have I done wrong here?

**Comment by MordredXYZ** [comment]
Nevermind, I left it do it's own thing for an hour while I ate dinner, reloaded it and now it works...?

I'mma just back away and not turn this machine off, ever. Closed I guess!

**Comment by drweissbrot** [comment]
It's showing the green background, so I think the HUD actually worked fine.
Were you in the server playing with the bots by any chance? The game doesn't send out much data if you yourself are playing, so the HUD can't show a lot :)

**Comment by MordredXYZ** [comment]
Funnily enough, I just walked away, ate dinner and came back to the server and the HUD was working. Changed nothing.

I'll just say the dedicated server instance was haunted and put it with that? HAHA
