### ISSUE TITLE
Unable to Access HUD from Local Network

### ISSUE THREAD

**Issue by MordredXYZ** [drweissbrot/cs-hud#79]
Heyo!

First off, I absolutely LOVE this HUD so frickin much. Well done!

Just a slight point of pain is being unable to manipulate the HUD from another machine on my network, so I can avoid showing my configs on stream (I use a capture card for my observer machine) and I was hoping to work out why I'm unable to access the HUD instance externally?

I've opened up port 31982 on the machine running the HUD, but I'm still unable to access it externally on the local network. Any clues as to what I'm doing wrong?

**Comment by drweissbrot** [comment]
Try providing a host to bind to, either by
1. starting the HUD with a `HOST` environment variable, e.g. `HOST=0.0.0.0 ./cs-hud-linux`
2. setting a host in your `userspace/theme.json`, e.g. `{ "parent": "fennec", "host": "0.0.0.0" }`

You can also use the IP you use to connect to the that's machine hosting the HUD.
Note that either will allow all connections, so not a good idea if someone you don't trust is on the same network as you.

This is currently undocumented I think; let me know if it works and I'll write it up somewhere :D

**Comment by MordredXYZ** [comment]
Appending a host variable as you mentioned in option 2 worked perfectly. I've only got my own devices on my network, so having things open is fine.

Thanks for all your hard work, I can't wait to take this for a spin tomorrow night! I'll be broadcasting some ESL Australia ANZ Main CS2 matches using your HUD and I'll be sure to attribute it on my twitch :D
