### ISSUE TITLE
ADR seems to be bugged on one side

### ISSUE THREAD

**Issue by 29j2003** [drweissbrot/cs-hud#81]
As seen in the screenshot, the ADR for the CTs aren't displayed, while for the Ts they are. 
Only tested in a CS2 demo using the newest version of the hud. 
![image](https://github.com/drweissbrot/cs-hud/assets/44442596/d552e9de-1028-4314-8ae3-8fbcfc2a8f10)

**Comment by drweissbrot** [comment]
could you share the demo file you're using?

**Comment by 29j2003** [comment]
[demotestv1.zip](https://github.com/drweissbrot/cs-hud/files/12777764/demotestv1.zip)
Here you go - this is the one where I've tested it with the screenshot, though I am certain that I've encountered the problem in a different demo too.

**Comment by drweissbrot** [comment]
@29j2003 looks like the file you uploaded is empty, could you try again please? :D

**Comment by 29j2003** [comment]
https://leetify.com/app/match-details/844af22a-deaa-45ce-ba30-f49b8f8acdcd/overview It appears that GitHub removed the DEM-File, so I've just posted the leetify match where you can download it directly from if that is okay!
