### ISSUE TITLE
invalid map name

### ISSUE THREAD

**Issue by 42Firehawk** [drweissbrot/cs-hud#87]
When attempting to run the hud on a dathost match via gotv the hud would launch for web view (the display capture didn't seem to function appropriately but may be an issue on my end) but without the GSI to show the hud itself. Checking in console for manually launching the config would get an error: "[Console] map 1: invalid map name", and after removing the map GSI element and relaunching the hud it appeared to be at least partially functional.

**Comment by 42Firehawk** [comment]
the hud console was also giving this error repeatedly, which I forgot to paste in before sharing:

  TypeError: Cannot read properties of undefined (reading 'activity')
      at updateRoundDamages (C:\snapshot\app\cs-hud.js)
      at updateAdditionalState (C:\snapshot\app\cs-hud.js)
      at C:\snapshot\app\cs-hud.js
      at dispatch (C:\snapshot\app\cs-hud.js)
      at C:\snapshot\app\cs-hud.js
      at dispatch (C:\snapshot\app\cs-hud.js)
      at C:\snapshot\app\cs-hud.js
      at dispatch2 (C:\snapshot\app\cs-hud.js)
      at dispatch (C:\snapshot\app\cs-hud.js)
      at bodyParser2 (C:\snapshot\app\cs-hud.js)

**Comment by drweissbrot** [comment]
For the bit from your second comment, I think I know what's going on, and will try a guesstimated fix.
For the rest, I'm not sure if I completely understand :D

Where did you put `gamestate_integration_drweissbrot_hud.cfg`, on your client machine or the Dathost server?
If client, did you restart the game after saving the file? If server, I've never tried that, but would assume it also needs a restart of the server software, if it works at all.

> `[Console] map 1: invalid map name`

When exactly did you get this error? It sounds like you tried to run `exec gamestate_integration_drweissbrot_hud` in the console -- you don't need to do that, and it shouldn't work :D The game will read the file when it starts.

> after removing the map GSI element

Do you mean you removed `"map" "1"` from `gamestate_integration_drweissbrot_hud.cfg`?

> it appeared to be at least partially functional

What exactly wasn't working? :D

**Comment by 42Firehawk** [comment]
The cfg was on the client machine, and I simply restarted the game after removing "map" "1" from the cfg. I manually exec'd the cfg to give an attempt at figuring out why I was seeing nothing, and after making the change and restarting it appeared to work normally. I simply said partially because of the assumption that removing part of the payload *should* break things.

**Comment by drweissbrot** [comment]
Ahh, I think I know what's happening now.

Try adding `"map" "1"` back into the config file (and restart your CS client); your assumption is right, if it's missing, everything should be broken (as in, literally no HUD element should show up actually).

If you see the `TypeError: Cannot read properties of undefined (reading 'activity')` in the HUD's console again, load a map/demo or connect to a GOTV server, then Ctrl+C the HUD and restart it.
As mentioned, will try a fix for this tomorrow.

**Comment by drweissbrot** [comment]
I couldn't reproduce the original issue, but if you're still encountering it, give latest `master` a try and let me know if that fixes it :)

**Comment by 42Firehawk** [comment]
From what I can tell it was entirely something I fucked up on my end, running it again fixed it all
