### ISSUE TITLE
app automatically exits

### ISSUE THREAD

**Issue by Dom862** [drweissbrot/cs-hud#91]
when i try to open the app (the one from the zip file), it opens then exits by its own
how can i solve dis?

**Comment by drweissbrot** [comment]
I assume this is the `cs-hud-win32-x64.zip`, not config or radar?
Currently the EXE from `cs-hud-win32-x64.zip` will not show anything if you're not spectating a CS match, so maybe it is running and just invisible.

If you run both the EXE and CS, and you're spectating a match in CS, does it still not show anything? You may need to Alt+Tab to the HUD window.

Note that you cannot be playing yourself. You need to be either watching a demo, watching CSTV/GOTV, or spectating a live match. Easiest way: Start an offline match versus bots, then join the Spectators team.

**Comment by Dom862** [comment]
can't see anythign when spectating a match, hud window doesn't even pop up

**Comment by drweissbrot** [comment]
Interesting... :/ I don't have a Windows machine available right now unfortunately, so could you try running the EXE from the command line?

I think you can do that by Ctrl+Shift+Right-clicking in the Explorer window where the EXE is, then selecting something like `Open Powershell`. In the blue window that opens up, type `cmd`, press Enter, then `cs-hud.exe`, then press Enter again.
Could you then copy the output of that in here (or take a screenshot)?

**Comment by Dom862** [comment]
sure wait

**Comment by Dom862** [comment]
![bug](https://github.com/drweissbrot/cs-hud/assets/120901406/538887ac-96cd-4e88-973e-a98d41e7d6ad)

**Comment by drweissbrot** [comment]
You're not running this in a virtual machine or anything, right? If you are, that might be the issue :D

Assuming you're not in a VM though, a couple things you could try:
1. Move the entire folder to the `C:` drive.
2. Run `cs-hud.exe --disable-gpu`. Will probably work, but will probably also make animations in the HUD choppy.
3. Run `cs-hud.exe --no-sandbox`.

Do any of these work?

**Comment by Dom862** [comment]
moved the entire thing to my c drive and it opens, but it not showing the overlay

**Comment by drweissbrot** [comment]
If you mean that the window shows up in the taskbar/Alt+Tab but there's nothing is in there:
What do you see when you open http://localhost:31982/hud in your browser?

If you mean that the window doesn't show up at all, could you do the `cmd` thing again and post the output again?

**Comment by Dom862** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/120901406/523a5acf-d7b2-4499-93e9-758745766309)

**Comment by Dom862** [comment]
just got the app overlay working, but it is flickering a lot

**Comment by drweissbrot** [comment]
Welp at least it's kinda working :D
Could you kill and restart the EXE from the ZIP file? But keep `cs-hud-win.exe` (the one that opens a console by itself) running.

**Comment by Dom862** [comment]
![image](https://github.com/drweissbrot/cs-hud/assets/120901406/016fcba8-f305-48ff-ac12-67951e40034d)

**Comment by drweissbrot** [comment]
@42Firehawk have you seen something like this by any chance?

**Comment by 42Firehawk** [comment]
I haven't had issues with it not launching, and do run it from a secondary drive (D in my case), and definitely no issues with a black box covering a large portion of my display. The only thing I do see is no spec or observer cfg to clear the default hud out (like draw_only_deathnotices or smth). But the black screen I haven't seen ever before.

**Comment by drweissbrot** [comment]
Gonna close this for now as it seems out of the HUD's control, but feel free to reopen if you're still having trouble :)
