### ISSUE TITLE
Green background 

### ISSUE THREAD

**Issue by Morales-1337** [drweissbrot/cs-hud#93]
How is it possible to overlay the browser with the transparency of the green?

**Comment by drweissbrot** [comment]
If you're using a browser source in OBS or something along those lines, make sure you add `?transparent` to the URL. cf. https://github.com/drweissbrot/cs-hud/blob/d85dcd87db009d29bac9e2c34eab927d89690ab1/readme.md

You can't just open the website in your browser and put it on top of the game, if that's what you're trying to do; see https://github.com/drweissbrot/cs-hud/blob/d85dcd87db009d29bac9e2c34eab927d89690ab1/readme.md#fullscreen-windowed for instructions.

Does this help? If not, please describe how you're trying to use it.

**Comment by drweissbrot** [comment]
Will close for now, feel free to reopen if you're still having trouble :)
