### ISSUE TITLE
GSI does not send to HUD when not spectating player

### ISSUE THREAD

**Issue by loganramhap** [drweissbrot/cs-hud#95]
When using the hud for free cam, the hid "freezes" when you're not on a player and "catches up" once you go back onto a player. Makes it hard to run 2 observers as observer lerps don't exist anymore

**Comment by 42Firehawk** [comment]
Ran demo locally to test and cannot reproduce while running hud via yarn, however bug exists when running the compiled version.

**Comment by drweissbrot** [comment]
I can't really reproduce this; everything seems to work fine for me when flying around the map in a demo, both via yarn (on master) and the pre-built binary (both master and 2.1.1).

The only thing I'm seeing is that the focused player thing in the bottom center remains on the player you spectated before; logged as #102.

**Comment by drweissbrot** [comment]
Is this still an issue on [v2.3.0](https://github.com/drweissbrot/cs-hud/releases/tag/v2.3.0)?

**Comment by drweissbrot** [comment]
Gonna close this one for now, feel free to reopen if you're still seeing this.
