### ISSUE TITLE
Dead players on minimap disappearing

### ISSUE THREAD

**Issue by drweissbrot** [drweissbrot/cs-hud#97]
(Not verified yet, someone told me they noticed this.)

The `X` icon for dead players on the minimap disappears pretty quickly. Might be a bug in the HUD that removes them, or might be GSI not sending dead players after a bit.

May be related to or duplicate of #92.

**Comment by 42Firehawk** [comment]
From using in live games: the dead player location updates to whatever living player they are spectating, at least that is my assumption since the X for the dead player will float directly underneath a living player on the same team.
