### ISSUE TITLE
Player numbers goes wrong

### ISSUE THREAD

**Issue by Rontt1** [drweissbrot/cs-hud#98]
Player numbers goes 1234056789 for some reason. And player who seems to be #0 is really #1 and player #1 is really #2 and so on. Atleast last game that I streamed. Is there any quick fix that I can do myself? Im totally noob with this thing thought...

![kuva](https://github.com/drweissbrot/cs-hud/assets/151652992/a7c629ad-19e4-4a5b-abc9-2b8e50a74c21)

**Comment by 42Firehawk** [comment]
This bug is new as to the most recent update, which shifted all player numbers. Most likely this is a change to the GSI array, as similar issues were seen in other huds.
